import { GeoLocation } from '../types/tactical';

export const WORLD_LOCATIONS: GeoLocation[] = [
  // ==========================================
  // --- UNITED STATES OF AMERICA (PRIMARY) ---
  // ==========================================
  {
    id: 'usa-washington',
    name: 'Washington, D.C.',
    region: 'National Capital Region',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 38.8951,
    lng: -77.0364,
    theaterType: 'Capital Defense Theater',
    defenseGrade: 'OMEGA',
    description: 'Pentagon & NCR Integrated Air Defense System with NASAMS and Andrews AFB fighters.',
    silosCount: 8,
    shipsCount: 2,
    jetsCount: 8,
  },
  {
    id: 'usa-newyork',
    name: 'New York City',
    region: 'Atlantic Coast Sector',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 40.7128,
    lng: -74.006,
    theaterType: 'Metropolitan Air Shield',
    defenseGrade: 'OMEGA',
    description: 'Atlantic coastal early warning radar network & air defense perimeter.',
    silosCount: 6,
    shipsCount: 4,
    jetsCount: 8,
  },
  {
    id: 'usa-norad',
    name: 'Colorado Springs / NORAD',
    region: 'Cheyenne Mountain Complex',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 38.8339,
    lng: -104.8214,
    theaterType: 'Strategic Missile Early Warning',
    defenseGrade: 'OMEGA',
    description: 'Central Strategic Missile Early Warning Network commanding GMD interceptor silos.',
    silosCount: 8,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'usa-losangeles',
    name: 'Los Angeles',
    region: 'Pacific Coast Sector',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 34.0522,
    lng: -118.2437,
    theaterType: 'Pacific Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'Vandenberg Space Force Base missile tracking and coastal defense grid.',
    silosCount: 6,
    shipsCount: 4,
    jetsCount: 6,
  },
  {
    id: 'usa-pearlharbor',
    name: 'Pearl Harbor / Honolulu',
    region: 'Hawaii / USINDOPACOM',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 21.3496,
    lng: -157.9744,
    theaterType: 'Central Pacific Naval Fleet',
    defenseGrade: 'OMEGA',
    description: 'US Indo-Pacific Fleet headquarters with Aegis Ashore missile defense installations.',
    silosCount: 6,
    shipsCount: 6,
    jetsCount: 8,
  },
  {
    id: 'usa-sandiego',
    name: 'San Diego',
    region: 'Naval Base Coronado',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 32.7157,
    lng: -117.1611,
    theaterType: 'Pacific Fleet Carrier Base',
    defenseGrade: 'ALPHA',
    description: 'Nimitz-class carrier strike groups and naval aviation air defense grid.',
    silosCount: 4,
    shipsCount: 6,
    jetsCount: 6,
  },
  {
    id: 'usa-seattle',
    name: 'Seattle / Puget Sound',
    region: 'Naval Base Kitsap',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 47.6062,
    lng: -122.3321,
    theaterType: 'Pacific Northwest Strategic Submarine Base',
    defenseGrade: 'OMEGA',
    description: 'Ohio-class strategic ballistic submarine hub and northern air interceptor base.',
    silosCount: 6,
    shipsCount: 4,
    jetsCount: 6,
  },
  {
    id: 'usa-chicago',
    name: 'Chicago',
    region: 'Great Lakes Defense Sector',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 41.8781,
    lng: -87.6298,
    theaterType: 'Inland Strategic Air Corridor',
    defenseGrade: 'ALPHA',
    description: 'Midwest integrated air defense radar and tactical response squadrons.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'usa-miami',
    name: 'Miami',
    region: 'Florida / USSOUTHCOM',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 25.7617,
    lng: -80.1918,
    theaterType: 'Caribbean Maritime Defense',
    defenseGrade: 'ALPHA',
    description: 'Southern air interceptor sector and naval coastal surveillance.',
    silosCount: 4,
    shipsCount: 3,
    jetsCount: 4,
  },
  {
    id: 'usa-houston',
    name: 'Houston',
    region: 'Texas / Gulf Coast',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 29.7604,
    lng: -95.3698,
    theaterType: 'Gulf Coast Energy Defense Hub',
    defenseGrade: 'ALPHA',
    description: 'Gulf of Mexico coastal missile tracking and aerospace defense.',
    silosCount: 4,
    shipsCount: 2,
    jetsCount: 4,
  },

  // ==========================================
  // --- UNITED KINGDOM & EUROPE ---
  // ==========================================
  {
    id: 'uk-london',
    name: 'London',
    region: 'Greater London / Northwood HQ',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    lat: 51.5074,
    lng: -0.1278,
    theaterType: 'Capital Defense Theater',
    defenseGrade: 'OMEGA',
    description: 'Sky Sabre air defense missile network and RAF Quick Reaction Alert interceptors.',
    silosCount: 6,
    shipsCount: 4,
    jetsCount: 8,
  },
  {
    id: 'uk-portsmouth',
    name: 'Portsmouth / Royal Navy Base',
    region: 'English Channel',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    lat: 50.8198,
    lng: -1.088,
    theaterType: 'Royal Navy Fleet Headquarters',
    defenseGrade: 'ALPHA',
    description: 'HMS Queen Elizabeth carrier strike group and Type 45 Daring-class air defense destroyers.',
    silosCount: 4,
    shipsCount: 6,
    jetsCount: 6,
  },
  {
    id: 'uk-manchester',
    name: 'Manchester',
    region: 'Northern Defense Sector',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    lat: 53.4808,
    lng: -2.2426,
    theaterType: 'Industrial Sector Air Shield',
    defenseGrade: 'ALPHA',
    description: 'Central UK airspace monitoring radar and rapid interceptor base.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'uk-edinburgh',
    name: 'Edinburgh / RAF Lossiemouth',
    region: 'Scotland / North Sea',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    lat: 55.9533,
    lng: -3.1883,
    theaterType: 'North Sea Defense Sector',
    defenseGrade: 'ALPHA',
    description: 'Eurofighter Typhoon interceptors and Poseidon maritime patrol aircraft.',
    silosCount: 4,
    shipsCount: 2,
    jetsCount: 6,
  },
  {
    id: 'uk-gibraltar',
    name: 'Gibraltar',
    region: 'Strait of Gibraltar Outpost',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    lat: 36.1408,
    lng: -5.3536,
    theaterType: 'Strategic Maritime Chokepoint',
    defenseGrade: 'OMEGA',
    description: 'Strategic Mediterranean naval base with coastal tracking radar.',
    silosCount: 4,
    shipsCount: 3,
    jetsCount: 4,
  },

  // ==========================================
  // --- JAPAN & EAST ASIA ---
  // ==========================================
  {
    id: 'japan-tokyo',
    name: 'Tokyo',
    region: 'Kanto Region / Tokyo Bay',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    lat: 35.6762,
    lng: 139.6503,
    theaterType: 'Capital Island Defense',
    defenseGrade: 'OMEGA',
    description: 'JSDF Patriot PAC-3 batteries & maritime Aegis destroyers in Tokyo Bay.',
    silosCount: 8,
    shipsCount: 4,
    jetsCount: 8,
  },
  {
    id: 'japan-okinawa',
    name: 'Okinawa / Kadena Air Base',
    region: 'Ryukyu Islands / US PACAF',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    lat: 26.3358,
    lng: 127.7675,
    theaterType: 'Keystone Pacific Outpost',
    defenseGrade: 'OMEGA',
    description: 'Hub of US Air Power in the Pacific with F-15EX, F-22 and Patriot batteries.',
    silosCount: 6,
    shipsCount: 4,
    jetsCount: 8,
  },
  {
    id: 'japan-osaka',
    name: 'Osaka',
    region: 'Kansai Region',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    lat: 34.6937,
    lng: 135.5023,
    theaterType: 'Industrial Coastal Hub',
    defenseGrade: 'ALPHA',
    description: 'Kansai maritime radar grid and air defense missile regiments.',
    silosCount: 4,
    shipsCount: 3,
    jetsCount: 4,
  },
  {
    id: 'japan-yokosuka',
    name: 'Yokosuka Naval Base',
    region: 'US 7th Fleet Headquarters',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    lat: 35.281,
    lng: 139.6722,
    theaterType: 'Forward Deployed Aircraft Carrier Base',
    defenseGrade: 'OMEGA',
    description: 'Home port of USS Ronald Reagan / George Washington carrier strike group.',
    silosCount: 6,
    shipsCount: 6,
    jetsCount: 8,
  },

  // ==========================================
  // --- GERMANY, FRANCE & EUROPEAN POWERS ---
  // ==========================================
  {
    id: 'germany-berlin',
    name: 'Berlin',
    region: 'Federal Republic of Germany',
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    lat: 52.52,
    lng: 13.405,
    theaterType: 'Central European Air Shield',
    defenseGrade: 'OMEGA',
    description: 'Arrow 3 & Patriot PAC-3 European Sky Shield initiative command hub.',
    silosCount: 6,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'france-paris',
    name: 'Paris',
    region: 'Île-de-France',
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    lat: 48.8566,
    lng: 2.3522,
    theaterType: 'Capital Strategic Defense',
    defenseGrade: 'OMEGA',
    description: 'SAMP/T Mamba surface-to-air missile systems and Rafale fighter squadrons.',
    silosCount: 6,
    shipsCount: 0,
    jetsCount: 8,
  },
  {
    id: 'israel-telaviv',
    name: 'Tel Aviv',
    region: 'Gush Dan / Central Sector',
    country: 'Israel',
    countryCode: 'IL',
    flag: '🇮🇱',
    lat: 32.0853,
    lng: 34.7818,
    theaterType: 'Multi-Layer Ballistic Shield',
    defenseGrade: 'OMEGA',
    description: 'Multi-tier Iron Dome, David Sling and Arrow 3 missile defense shield.',
    silosCount: 8,
    shipsCount: 2,
    jetsCount: 8,
  },

  // ==========================================
  // --- UKRAINE & EASTERN EUROPE ---
  // ==========================================
  {
    id: 'ukraine-kyiv',
    name: 'Kyiv',
    region: 'Kyiv Oblast',
    country: 'Ukraine',
    countryCode: 'UA',
    flag: '🇺🇦',
    lat: 50.4501,
    lng: 30.5234,
    theaterType: 'Capital Air Defense Fortress',
    defenseGrade: 'OMEGA',
    description: 'Layered Patriot, IRIS-T, NASAMS, and Gepard air defense network.',
    silosCount: 8,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'ukraine-odessa',
    name: 'Odesa',
    region: 'Black Sea Coast',
    country: 'Ukraine',
    countryCode: 'UA',
    flag: '🇺🇦',
    lat: 46.4825,
    lng: 30.7233,
    theaterType: 'Black Sea Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'Coastal anti-ship missile defense grid and tactical air cover.',
    silosCount: 4,
    shipsCount: 2,
    jetsCount: 4,
  },

  // ==========================================
  // --- RUSSIA ---
  // ==========================================
  {
    id: 'russia-moscow',
    name: 'Moscow',
    region: 'Central Federal District',
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    lat: 55.7558,
    lng: 37.6173,
    theaterType: 'Strategic Anti-Ballistic Ring',
    defenseGrade: 'OMEGA',
    description: 'A-235 Nudol strategic ABM shield, S-400 and S-500 air defense rings.',
    silosCount: 8,
    shipsCount: 0,
    jetsCount: 8,
  },
  {
    id: 'russia-stpetersburg',
    name: 'St. Petersburg',
    region: 'Baltic Naval Sector',
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    lat: 59.9343,
    lng: 30.3351,
    theaterType: 'Baltic Naval Air Defense',
    defenseGrade: 'ALPHA',
    description: 'Gulf of Finland naval defense corridor and early warning radar.',
    silosCount: 4,
    shipsCount: 4,
    jetsCount: 4,
  },

  // ==========================================
  // --- MIDDLE EAST & ASIA PACIFIC ---
  // ==========================================
  {
    id: 'korea-seoul',
    name: 'Seoul',
    region: 'Gyeonggi / DMZ Perimeter',
    country: 'South Korea',
    countryCode: 'KR',
    flag: '🇰🇷',
    lat: 37.5665,
    lng: 126.978,
    theaterType: 'Frontier Air Defense Shield',
    defenseGrade: 'OMEGA',
    description: 'KAMD (Korea Air and Missile Defense), Patriot PAC-3 and THAAD batteries.',
    silosCount: 8,
    shipsCount: 3,
    jetsCount: 8,
  },
  {
    id: 'taiwan-taipei',
    name: 'Taipei',
    region: 'Taiwan Strait Defense',
    country: 'Taiwan',
    countryCode: 'TW',
    flag: '🇹🇼',
    lat: 25.033,
    lng: 121.5654,
    theaterType: 'Island Fortress Air Defense',
    defenseGrade: 'OMEGA',
    description: 'Sky Bow III (Tien Kung) and Patriot PAC-3 high-density missile defense ring.',
    silosCount: 6,
    shipsCount: 4,
    jetsCount: 6,
  },
  {
    id: 'australia-sydney',
    name: 'Sydney',
    region: 'Fleet Base East',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    lat: -33.8688,
    lng: 151.2093,
    theaterType: 'Southern Ocean Maritime Defense',
    defenseGrade: 'ALPHA',
    description: 'Hobart-class air warfare destroyers and Jindalee Operational Radar Network (JORN).',
    silosCount: 4,
    shipsCount: 4,
    jetsCount: 4,
  },
  {
    id: 'uae-dubai',
    name: 'Dubai',
    region: 'Persian Gulf Sector',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    lat: 25.2048,
    lng: 55.2708,
    theaterType: 'Gulf Aerospace Defense Sector',
    defenseGrade: 'ALPHA',
    description: 'THAAD and Patriot batteries defending Persian Gulf maritime approaches.',
    silosCount: 4,
    shipsCount: 2,
    jetsCount: 4,
  },
];

export function searchLocations(query: string): GeoLocation[] {
  if (!query || query.trim() === '') {
    return WORLD_LOCATIONS.slice(0, 10);
  }

  const q = query.toLowerCase().trim();

  return WORLD_LOCATIONS.filter((loc) => {
    return (
      loc.name.toLowerCase().includes(q) ||
      loc.country.toLowerCase().includes(q) ||
      loc.region.toLowerCase().includes(q) ||
      loc.theaterType.toLowerCase().includes(q) ||
      loc.countryCode.toLowerCase() === q
    );
  });
}

export function findNearestLocation(lat: number, lng: number): GeoLocation {
  let nearest = WORLD_LOCATIONS[0];
  let minDistance = Infinity;

  WORLD_LOCATIONS.forEach((loc) => {
    const dLat = loc.lat - lat;
    const dLng = loc.lng - lng;
    const dist = Math.sqrt(dLat * dLat + dLng * dLng);
    if (dist < minDistance) {
      minDistance = dist;
      nearest = loc;
    }
  });

  return nearest;
}
