import { GeoLocation } from '../types/tactical';

export const WORLD_LOCATIONS: GeoLocation[] = [
  // --- INDIA & SOUTH ASIA ---
  {
    id: 'india-delhi',
    name: 'New Delhi',
    region: 'National Capital Region',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 28.6139,
    lng: 77.209,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'OMEGA',
    description: 'S-400 Triumf & Advanced Air Defence (AAD) Ballistic Missile Shield over the National Capital.',
    silosCount: 6,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'india-mumbai',
    name: 'Mumbai',
    region: 'Western Naval Command',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 18.922,
    lng: 72.8347,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'INS Vikrant Aircraft Carrier strike group and Kolkata-class guided missile destroyers guarding the Arabian Sea.',
    silosCount: 3,
    shipsCount: 4,
    jetsCount: 4,
  },
  {
    id: 'india-chandigarh',
    name: 'Chandigarh / Western Air Command',
    region: 'Northern Defense Sector',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 30.7333,
    lng: 76.7794,
    theaterType: 'Northern Defense Sector',
    defenseGrade: 'ALPHA',
    description: 'Frontline Su-30MKI and Rafale interceptor air squadrons guarding Himalayan air corridors.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'india-vizag',
    name: 'Visakhapatnam',
    region: 'Eastern Naval Command',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 17.6868,
    lng: 83.2185,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'BRAVO',
    description: 'Bay of Bengal strategic submarine base with long-range coastal radar tracking networks.',
    silosCount: 3,
    shipsCount: 3,
    jetsCount: 3,
  },

  // --- UNITED STATES ---
  {
    id: 'usa-washington',
    name: 'Washington, D.C.',
    region: 'National Capital Region',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 38.8951,
    lng: -77.0364,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'OMEGA',
    description: 'Integrated Air Defense System (NCR-IADS) with NASAMS, Avenger batteries, and Andrews AFB interceptors.',
    silosCount: 6,
    shipsCount: 2,
    jetsCount: 6,
  },
  {
    id: 'usa-norad',
    name: 'Colorado Springs / NORAD Cheyenne Mountain',
    region: 'North American Aerospace Defense',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 38.8339,
    lng: -104.8214,
    theaterType: 'Strategic Air Base',
    defenseGrade: 'OMEGA',
    description: 'Central Strategic Missile Early Warning Network commanding Ground-Based Midcourse Defense (GMD) silos.',
    silosCount: 8,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'usa-sandiego',
    name: 'San Diego / Pacific Fleet',
    region: 'Southern California Maritime',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 32.7157,
    lng: -117.1611,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'Nimitz-class supercarrier fleet with Aegis Ballistic Missile Defense destroyers in the Pacific.',
    silosCount: 3,
    shipsCount: 5,
    jetsCount: 5,
  },
  {
    id: 'usa-pearlharbor',
    name: 'Pearl Harbor / Honolulu',
    region: 'Central Pacific Command',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 21.3496,
    lng: -157.9744,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'PACAF F-22 Raptor airbase and Aegis Ashore missile interceptor testing facility.',
    silosCount: 4,
    shipsCount: 4,
    jetsCount: 4,
  },

  // --- RUSSIA & EURASIA ---
  {
    id: 'russia-moscow',
    name: 'Moscow',
    region: 'Central Aerospace Defense',
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    lat: 55.7558,
    lng: 37.6173,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'OMEGA',
    description: 'A-135 / A-235 Amur strategic anti-ballistic missile system backed by Don-2N phased array radar.',
    silosCount: 8,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'russia-stpetersburg',
    name: 'Saint Petersburg / Baltic Sector',
    region: 'Northwestern Command',
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    lat: 59.9343,
    lng: 30.3351,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'Baltic Fleet naval missile frigates and S-400 coastal SAM batteries.',
    silosCount: 4,
    shipsCount: 3,
    jetsCount: 4,
  },
  {
    id: 'russia-vladivostok',
    name: 'Vladivostok / Pacific Rim',
    region: 'Far Eastern Maritime Sector',
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    lat: 43.1155,
    lng: 131.8855,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'Pacific Fleet submarine base and long-range Voronezh radar station.',
    silosCount: 4,
    shipsCount: 4,
    jetsCount: 4,
  },

  // --- UKRAINE & EASTERN EUROPE ---
  {
    id: 'ukraine-kyiv',
    name: 'Kyiv',
    region: 'Central Air Defense Zone',
    country: 'Ukraine',
    countryCode: 'UA',
    flag: '🇺🇦',
    lat: 50.4501,
    lng: 30.5234,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'ALPHA',
    description: 'Layered Patriot PAC-3, IRIS-T SLM, and SAMP/T anti-ballistic missile umbrella.',
    silosCount: 5,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'ukraine-odesa',
    name: 'Odesa',
    region: 'Black Sea Defense Command',
    country: 'Ukraine',
    countryCode: 'UA',
    flag: '🇺🇦',
    lat: 46.4825,
    lng: 30.7233,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'BRAVO',
    description: 'Coastal Neptune anti-ship missile batteries and maritime drone strike control center.',
    silosCount: 3,
    shipsCount: 2,
    jetsCount: 3,
  },

  // --- IRAN & MIDDLE EAST ---
  {
    id: 'iran-tehran',
    name: 'Tehran',
    region: 'Central Strategic Sector',
    country: 'Iran',
    countryCode: 'IR',
    flag: '🇮🇷',
    lat: 35.6892,
    lng: 51.389,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'ALPHA',
    description: 'Bavar-373 and S-300PMU2 high-altitude SAM missile networks guarding nuclear facilities.',
    silosCount: 6,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'iran-hormuz',
    name: 'Bandar Abbas / Strait of Hormuz',
    region: 'Persian Gulf Maritime',
    country: 'Iran',
    countryCode: 'IR',
    flag: '🇮🇷',
    lat: 27.1832,
    lng: 56.2666,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'Strategic chokepoint naval missile batteries and swarm missile boat bases.',
    silosCount: 4,
    shipsCount: 4,
    jetsCount: 3,
  },
  {
    id: 'israel-telaviv',
    name: 'Tel Aviv / Central District',
    region: 'Iron Dome National Grid',
    country: 'Israel',
    countryCode: 'IL',
    flag: '🇮🇱',
    lat: 32.0853,
    lng: 34.7818,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'OMEGA',
    description: 'Multi-tier Arrow 3, David’s Sling, and Iron Dome anti-rocket defense shield.',
    silosCount: 6,
    shipsCount: 2,
    jetsCount: 5,
  },
  {
    id: 'uae-dubai',
    name: 'Dubai / Abu Dhabi',
    region: 'Arabian Peninsula Command',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    lat: 25.2048,
    lng: 55.2708,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'THAAD Terminal High Altitude Area Defense and Patriot PAC-3 missile installations.',
    silosCount: 4,
    shipsCount: 3,
    jetsCount: 4,
  },

  // --- EAST ASIA ---
  {
    id: 'china-beijing',
    name: 'Beijing',
    region: 'Northern Theater Command',
    country: 'China',
    countryCode: 'CN',
    flag: '🇨🇳',
    lat: 39.9042,
    lng: 116.4074,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'OMEGA',
    description: 'HQ-9B and HQ-19 midcourse anti-ballistic missile perimeter with high-power phased arrays.',
    silosCount: 7,
    shipsCount: 2,
    jetsCount: 6,
  },
  {
    id: 'china-shanghai',
    name: 'Shanghai / East Sea',
    region: 'Eastern Theater Command',
    country: 'China',
    countryCode: 'CN',
    flag: '🇨🇳',
    lat: 31.2304,
    lng: 121.4737,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'Type 055 guided missile cruiser flotilla and coastal hypersonic defense radar grid.',
    silosCount: 4,
    shipsCount: 5,
    jetsCount: 5,
  },
  {
    id: 'japan-tokyo',
    name: 'Tokyo',
    region: 'Kanto Air Defense Sector',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    lat: 35.6762,
    lng: 139.6503,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'OMEGA',
    description: 'JASDF PAC-3 batteries in Ichigaya and JMSDF Maya-class Aegis destroyers with SM-3 Block IIA.',
    silosCount: 5,
    shipsCount: 4,
    jetsCount: 5,
  },
  {
    id: 'taiwan-taipei',
    name: 'Taipei',
    region: 'Taiwan Strait Defense',
    country: 'Taiwan',
    countryCode: 'TW',
    flag: '🇹🇼',
    lat: 25.033,
    lng: 121.5654,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'ALPHA',
    description: 'Tien-Kung III (Sky Bow) and Patriot PAC-3 SAM network with Leshan EWR radar.',
    silosCount: 5,
    shipsCount: 3,
    jetsCount: 4,
  },
  {
    id: 'southkorea-seoul',
    name: 'Seoul',
    region: 'Capital Defense Command',
    country: 'South Korea',
    countryCode: 'KR',
    flag: '🇰🇷',
    lat: 37.5665,
    lng: 126.978,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'OMEGA',
    description: 'KAMD (Korea Air and Missile Defense) with Cheongung II (L-SAM) and THAAD batteries.',
    silosCount: 6,
    shipsCount: 2,
    jetsCount: 5,
  },

  // --- WESTERN EUROPE ---
  {
    id: 'uk-london',
    name: 'London',
    region: 'RAF Air Defense Sector',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    lat: 51.5074,
    lng: -0.1278,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'ALPHA',
    description: 'RAF Coningsby Typhoon QRA scramble wing and Type 45 Daring-class air defense destroyers.',
    silosCount: 4,
    shipsCount: 4,
    jetsCount: 5,
  },
  {
    id: 'france-paris',
    name: 'Paris',
    region: 'French Air and Space Force',
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    lat: 48.8566,
    lng: 2.3522,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'ALPHA',
    description: 'SAMP/T Mamba missile batteries and Rafale B nuclear deterrent scramble units.',
    silosCount: 4,
    shipsCount: 2,
    jetsCount: 5,
  },
  {
    id: 'germany-berlin',
    name: 'Berlin',
    region: 'European Sky Shield Initiative',
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    lat: 52.52,
    lng: 13.405,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'ALPHA',
    description: 'Arrow 3 and IRIS-T SLM central European strategic air defense command node.',
    silosCount: 4,
    shipsCount: 1,
    jetsCount: 4,
  },

  // --- OCEANIA & AMERICAS ---
  {
    id: 'australia-sydney',
    name: 'Sydney / Eastern Seaboard',
    region: 'Royal Australian Navy Command',
    country: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    lat: -33.8688,
    lng: 151.2093,
    theaterType: 'Coastal / Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'JORN Over-The-Horizon radar system and Hobart-class Aegis guided missile destroyers.',
    silosCount: 4,
    shipsCount: 4,
    jetsCount: 4,
  },
  {
    id: 'brazil-brasilia',
    name: 'Brasília / Amazon Command',
    region: 'South American Defense Grid',
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    lat: -15.7975,
    lng: -47.8919,
    theaterType: 'Capital / Urban Theater',
    defenseGrade: 'BRAVO',
    description: 'CINDACTA integrated air traffic and airspace surveillance defense network with Gripen E fighters.',
    silosCount: 3,
    shipsCount: 2,
    jetsCount: 3,
  }
];

export function searchLocations(query: string): GeoLocation[] {
  if (!query || query.trim() === '') {
    return WORLD_LOCATIONS.slice(0, 8);
  }

  const q = query.toLowerCase().trim();

  return WORLD_LOCATIONS.filter((loc) => {
    return (
      loc.name.toLowerCase().includes(q) ||
      loc.country.toLowerCase().includes(q) ||
      loc.region.toLowerCase().includes(q) ||
      loc.theaterType.toLowerCase().includes(q) ||
      loc.countryCode.toLowerCase() === q
    );
  });
}

export function findNearestLocation(lat: number, lng: number): GeoLocation {
  let nearest = WORLD_LOCATIONS[0];
  let minDistance = Infinity;

  WORLD_LOCATIONS.forEach((loc) => {
    const dLat = loc.lat - lat;
    const dLng = loc.lng - lng;
    const dist = Math.sqrt(dLat * dLat + dLng * dLng);
    if (dist < minDistance) {
      minDistance = dist;
      nearest = loc;
    }
  });

  return nearest;
}
