import { GeoLocation } from '../types/tactical';

export const WORLD_LOCATIONS: GeoLocation[] = [
  // --- INDIA & SOUTH ASIA ---
  {
    id: 'india-delhi',
    name: 'New Delhi',
    region: 'National Capital Region',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 28.6139,
    lng: 77.209,
    theaterType: 'Capital Defense Theater',
    defenseGrade: 'OMEGA',
    description: 'S-400 Triumf & Advanced Air Defence (AAD) Ballistic Missile Shield.',
    silosCount: 6,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'india-palwal',
    name: 'Palwal / South NCR',
    region: 'Haryana',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 28.1447,
    lng: 77.3259,
    theaterType: 'Regional Defense Sector',
    defenseGrade: 'ALPHA',
    description: 'Southern NCR Air Defense Radar installation and Akash SAM batteries.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'india-faridabad',
    name: 'Faridabad',
    region: 'Haryana / NCR',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 28.4089,
    lng: 77.3178,
    theaterType: 'Industrial Defense Hub',
    defenseGrade: 'ALPHA',
    description: 'Industrial zone air shield guarding south NCR perimeter.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'india-gurugram',
    name: 'Gurugram',
    region: 'Haryana / Cyber City',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 28.4595,
    lng: 77.0266,
    theaterType: 'Strategic Tech Sector',
    defenseGrade: 'ALPHA',
    description: 'Strategic tech sector air corridor defense network.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'india-noida',
    name: 'Noida / Greater Noida',
    region: 'Uttar Pradesh / NCR',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 28.5355,
    lng: 77.391,
    theaterType: 'Eastern NCR Defense',
    defenseGrade: 'ALPHA',
    description: 'Hindon Air Base early warning radar corridor.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'india-mumbai',
    name: 'Mumbai',
    region: 'Western Naval Command',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 18.922,
    lng: 72.8347,
    theaterType: 'Maritime / Naval Theater',
    defenseGrade: 'ALPHA',
    description: 'INS Vikrant Aircraft Carrier strike group guarding Arabian Sea.',
    silosCount: 3,
    shipsCount: 4,
    jetsCount: 4,
  },
  {
    id: 'india-chandigarh',
    name: 'Chandigarh',
    region: 'Western Air Command',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 30.7333,
    lng: 76.7794,
    theaterType: 'Northern Air Base',
    defenseGrade: 'ALPHA',
    description: 'Frontline Su-30MKI and Rafale interceptor air squadrons.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'india-bengaluru',
    name: 'Bengaluru',
    region: 'Karnataka / Southern Command',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 12.9716,
    lng: 77.5946,
    theaterType: 'Aerospace Defense Hub',
    defenseGrade: 'ALPHA',
    description: 'HAL aerospace defense complex and southern surveillance radar.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'india-jaipur',
    name: 'Jaipur',
    region: 'Rajasthan / Western Sector',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 26.9124,
    lng: 75.7873,
    theaterType: 'Desert Border Theater',
    defenseGrade: 'ALPHA',
    description: 'Western desert border radar and surface-to-air batteries.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'india-kolkata',
    name: 'Kolkata',
    region: 'Eastern Command',
    country: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    lat: 22.5726,
    lng: 88.3639,
    theaterType: 'Eastern Defense Hub',
    defenseGrade: 'BRAVO',
    description: 'Bay of Bengal eastern sector air defense shield.',
    silosCount: 3,
    shipsCount: 2,
    jetsCount: 4,
  },

  // --- JAPAN & EAST ASIA ---
  {
    id: 'japan-tokyo',
    name: 'Tokyo',
    region: 'Kanto Region',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    lat: 35.6762,
    lng: 139.6503,
    theaterType: 'Capital / Island Defense',
    defenseGrade: 'OMEGA',
    description: 'JSDF PAC-3 batteries & maritime Aegis destroyers in Tokyo Bay.',
    silosCount: 6,
    shipsCount: 4,
    jetsCount: 6,
  },
  {
    id: 'japan-osaka',
    name: 'Osaka',
    region: 'Kansai Region',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    lat: 34.6937,
    lng: 135.5023,
    theaterType: 'Industrial Coastal Theater',
    defenseGrade: 'ALPHA',
    description: 'Kansai maritime early warning radar network.',
    silosCount: 4,
    shipsCount: 3,
    jetsCount: 4,
  },
  {
    id: 'japan-okinawa',
    name: 'Okinawa / Kadena Air Base',
    region: 'Ryukyu Islands',
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    lat: 26.3358,
    lng: 127.7675,
    theaterType: 'Strategic Island Outpost',
    defenseGrade: 'OMEGA',
    description: 'Key Pacific island air base with F-15/F-22 fighter wings.',
    silosCount: 6,
    shipsCount: 4,
    jetsCount: 8,
  },

  // --- UKRAINE & EASTERN EUROPE ---
  {
    id: 'ukraine-kyiv',
    name: 'Kyiv',
    region: 'Kyiv Oblast',
    country: 'Ukraine',
    countryCode: 'UA',
    flag: '🇺🇦',
    lat: 50.4501,
    lng: 30.5234,
    theaterType: 'Capital Air Defense Shield',
    defenseGrade: 'OMEGA',
    description: 'Layered Patriot, IRIS-T, NASAMS and Gepard air defense batteries.',
    silosCount: 6,
    shipsCount: 0,
    jetsCount: 6,
  },
  {
    id: 'ukraine-odessa',
    name: 'Odesa',
    region: 'Black Sea Coast',
    country: 'Ukraine',
    countryCode: 'UA',
    flag: '🇺🇦',
    lat: 46.4825,
    lng: 30.7233,
    theaterType: 'Black Sea Maritime Theater',
    defenseGrade: 'ALPHA',
    description: 'Coastal anti-ship missile batteries and port air defense network.',
    silosCount: 4,
    shipsCount: 2,
    jetsCount: 4,
  },

  // --- RUSSIA ---
  {
    id: 'russia-moscow',
    name: 'Moscow',
    region: 'Central Federal District',
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    lat: 55.7558,
    lng: 37.6173,
    theaterType: 'Capital Anti-Ballistic Ring',
    defenseGrade: 'OMEGA',
    description: 'A-135/A-235 Amur strategic ABM shield & S-400 rings.',
    silosCount: 8,
    shipsCount: 0,
    jetsCount: 8,
  },
  {
    id: 'russia-stpetersburg',
    name: 'St. Petersburg',
    region: 'Baltic Naval Sector',
    country: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    lat: 59.9343,
    lng: 30.3351,
    theaterType: 'Baltic Naval Theater',
    defenseGrade: 'ALPHA',
    description: 'Gulf of Finland naval air defense grid and early warning radar.',
    silosCount: 4,
    shipsCount: 4,
    jetsCount: 4,
  },

  // --- UNITED STATES ---
  {
    id: 'usa-washington',
    name: 'Washington, D.C.',
    region: 'National Capital Region',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 38.8951,
    lng: -77.0364,
    theaterType: 'Capital Defense Theater',
    defenseGrade: 'OMEGA',
    description: 'NCR Integrated Air Defense System with NASAMS and Andrews AFB fighters.',
    silosCount: 6,
    shipsCount: 2,
    jetsCount: 6,
  },
  {
    id: 'usa-norad',
    name: 'Colorado Springs / NORAD',
    region: 'Cheyenne Mountain Complex',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    lat: 38.8339,
    lng: -104.8214,
    theaterType: 'Strategic Missile Early Warning',
    defenseGrade: 'OMEGA',
    description: 'North American Aerospace Defense Command early warning center.',
    silosCount: 8,
    shipsCount: 0,
    jetsCount: 6,
  },

  // --- IRAN & MIDDLE EAST ---
  {
    id: 'iran-tehran',
    name: 'Tehran',
    region: 'Tehran Province',
    country: 'Iran',
    countryCode: 'IR',
    flag: '🇮🇷',
    lat: 35.6892,
    lng: 51.389,
    theaterType: 'Capital Mountain Theater',
    defenseGrade: 'ALPHA',
    description: 'Bavar-373 & S-300PMU2 strategic SAM rings surrounding capital.',
    silosCount: 6,
    shipsCount: 0,
    jetsCount: 4,
  },
  {
    id: 'iran-isfahan',
    name: 'Isfahan',
    region: 'Central Defense Sector',
    country: 'Iran',
    countryCode: 'IR',
    flag: '🇮🇷',
    lat: 32.6546,
    lng: 51.668,
    theaterType: 'Nuclear / Strategic Defense Sector',
    defenseGrade: 'ALPHA',
    description: '8th Tactical Air Base and layered SAM batteries.',
    silosCount: 4,
    shipsCount: 0,
    jetsCount: 4,
  },

  // --- UNITED KINGDOM & EUROPE ---
  {
    id: 'uk-london',
    name: 'London',
    region: 'Greater London',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    lat: 51.5074,
    lng: -0.1278,
    theaterType: 'Capital Air Defense',
    defenseGrade: 'ALPHA',
    description: 'Sky Sabre air defense systems and RAF Coningsby Typhoon QRA.',
    silosCount: 4,
    shipsCount: 3,
    jetsCount: 6,
  },
];

export function searchLocations(query: string): GeoLocation[] {
  if (!query || query.trim() === '') {
    return WORLD_LOCATIONS.slice(0, 8);
  }

  const q = query.toLowerCase().trim();

  return WORLD_LOCATIONS.filter((loc) => {
    return (
      loc.name.toLowerCase().includes(q) ||
      loc.country.toLowerCase().includes(q) ||
      loc.region.toLowerCase().includes(q) ||
      loc.theaterType.toLowerCase().includes(q) ||
      loc.countryCode.toLowerCase() === q
    );
  });
}

export function findNearestLocation(lat: number, lng: number): GeoLocation {
  let nearest = WORLD_LOCATIONS[0];
  let minDistance = Infinity;

  WORLD_LOCATIONS.forEach((loc) => {
    const dLat = loc.lat - lat;
    const dLng = loc.lng - lng;
    const dist = Math.sqrt(dLat * dLat + dLng * dLng);
    if (dist < minDistance) {
      minDistance = dist;
      nearest = loc;
    }
  });

  return nearest;
}
